sudo: required
dist: xenial
services:
- docker
install:
- docker build -t test .
script:
- docker run -ti test /bin/true
- docker run -ti test /bin/bash --version
- docker run -d -p 20:22 test && sleep 5
- echo ' ' | netcat localhost 20
notifications:
  email: false
  slack:
    secure: oi4J4l3Cuq+o0lea9MBmp4r11/l4Qo3jFlBrp3RDHPGe8toc4nvyNAzNbagme49UCH8RCsXSjUjl2JXG+5aPvUQJ+xtBf16gpai9MXEeWz3rIv1ktJSDwplg0xDXoLHUs2Pp30c+d+lwvm+5EiXVv53//uYPZ4cTTsO0zwj+vU8knsqXmMD4FpzVxBUbFlpFhkh0NShBChOpx1ZdlvvmVSMGs99s06Abau0m5UMASueNusXPW8T1/jXK+DaNNNzm0YOussOJGE0KAJfAILPylGS9Ogcy+Jk3GeVF0EQsPiuA4F6tdTiLAiK2IZUwacva02zsgmkcDJGLrnXfeYP5uijtuQvpOEwpXG6FH0w1n1WDSN1wboUs42NN+p533X/B1QlHuXz6ExF6Nvqzj9OP9hawmoo0r/frW6mq+r2pHSDMImmkBBbK2309Wf7rfoe/MvVwZqdDt1vunKuOmdY01oitoBagm4R6rlbuZcXnMFJL8JKRPZ53opkicxm6Yb9/4DM06R8CX720kvDtoqzAX90ZQ0nz7tZR5hSnIi3I4jNJx2wbdRf2pi3DszOgtdRoTCTZ2/oPw2TFR+GVeZEOD/CiIwBQsJqsCkl2IdicWu/fcVwVBhCgVaIIa06stH+WuzCHl+l66bkXgqiZDBUb+BXRWpy34fLAr5f+rro6MkE=
